# Generated by Django 4.2.2 on 2023-07-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_clickable', models.CharField(max_length=250, verbose_name='Номер (click)')),
                ('phone', models.CharField(max_length=250, verbose_name='Номер телефона')),
                ('vk', models.URLField(verbose_name='Вконтакте')),
                ('whatsapp', models.URLField(verbose_name='whatsapp')),
                ('odnoklassniki', models.URLField(verbose_name='Одноклассники')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('how_get', models.URLField(verbose_name='Как проехать')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='ContentCorp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan1', models.TextField(verbose_name='Заголовок')),
                ('slogan2', models.TextField(verbose_name='Подзаголовок')),
                ('pic', models.ImageField(upload_to='corp', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Контент "Corp"',
                'verbose_name_plural': 'Контент "Corp"',
            },
        ),
        migrations.CreateModel(
            name='ContentDdr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan1', models.TextField(verbose_name='Заголовок')),
                ('slogan2', models.TextField(verbose_name='Подзаголовок')),
                ('pic', models.ImageField(upload_to='ddr', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Контент "DDR"',
                'verbose_name_plural': 'Контент "DDR"',
            },
        ),
        migrations.CreateModel(
            name='ContentLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan1', models.TextField(verbose_name='Заголовок')),
                ('slogan2', models.TextField(verbose_name='Подзаголовок')),
                ('pic', models.ImageField(upload_to='landing', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Контент "Landing"',
                'verbose_name_plural': 'Контент "Landing"',
            },
        ),
        migrations.CreateModel(
            name='ContentVdr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan1', models.TextField(verbose_name='Заголовок')),
                ('slogan2', models.TextField(verbose_name='Подзаголовок')),
                ('pic', models.ImageField(upload_to='vdr', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Контент "VDR"',
                'verbose_name_plural': 'Контент "VDR"',
            },
        ),
        migrations.CreateModel(
            name='ContentVip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan1', models.TextField(verbose_name='Заголовок')),
                ('slogan2', models.TextField(verbose_name='Подзаголовок')),
                ('pic', models.ImageField(upload_to='vip', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Контент "VYP"',
                'verbose_name_plural': 'Контент "VYP"',
            },
        ),
        migrations.CreateModel(
            name='Corporativi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='corporativy', verbose_name='Корпоративы')),
            ],
            options={
                'verbose_name': 'Фотографии "Корпоративы"',
                'verbose_name_plural': 'Фотографии "Корпоративы"',
            },
        ),
        migrations.CreateModel(
            name='DniRozhdenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dni_rojdenia', verbose_name='Дни рождения')),
            ],
            options={
                'verbose_name': 'Фотографии "Дни рождения"',
                'verbose_name_plural': 'Фотографии "Дни рождения"',
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=250, verbose_name='Имя')),
                ('phone_number', models.CharField(max_length=250, verbose_name='Номер телефона')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заявки')),
                ('holiday_type', models.CharField(blank=True, max_length=250, verbose_name='Тип мероприятия')),
                ('guest_type', models.CharField(blank=True, max_length=250, verbose_name='Для кого')),
                ('guest_qty', models.IntegerField(blank=True, null=True, verbose_name='Количество гостей')),
                ('additions', models.TextField(blank=True, verbose_name='Доп.услуги')),
                ('present', models.CharField(blank=True, max_length=250, verbose_name='Подарок')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Заявки',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Prazdniki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='prazdniki', verbose_name='Праздники')),
            ],
            options={
                'verbose_name': 'Фотографии "Праздники"',
                'verbose_name_plural': 'Фотографии "Праздники"',
            },
        ),
        migrations.CreateModel(
            name='Present',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var', models.CharField(max_length=250, verbose_name='Вариант подарка')),
                ('img', models.ImageField(upload_to='landing', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Подарки',
                'verbose_name_plural': 'Подарки',
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=250, verbose_name='Тип ЮрЛица, название организации')),
                ('ogrn', models.CharField(max_length=250, verbose_name='ОГРН')),
                ('inn', models.CharField(max_length=250, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=250, verbose_name='КПП')),
                ('address', models.TextField(verbose_name='Юр. Адрес')),
            ],
            options={
                'verbose_name': 'Политика защиты и обработки',
                'verbose_name_plural': 'Политика защиты и обработки',
            },
        ),
        migrations.CreateModel(
            name='VideoOtzivy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(verbose_name='Видео отзыв')),
            ],
            options={
                'verbose_name': 'Видео отзывы',
                'verbose_name_plural': 'Видео отзывы',
            },
        ),
        migrations.CreateModel(
            name='Vipusknoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vipusknoy', verbose_name='Фото выпускного')),
            ],
            options={
                'verbose_name': 'Фотографии "Выпускной"',
                'verbose_name_plural': 'Фотографии "Выпускной"',
            },
        ),
        migrations.CreateModel(
            name='YandexApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url1', models.URLField(verbose_name='Ссылка1')),
                ('url2', models.URLField(verbose_name='Ссылка2')),
            ],
            options={
                'verbose_name': 'Яндекс API url',
                'verbose_name_plural': 'Яндекс API url',
            },
        ),
    ]
